### ISSUE TITLE
add option to disable cache for remote project rsync

### ISSUE THREAD

**Issue by sanderr** [inmanta/pytest-inmanta-lsm#272]
Because the remote orchestrator fixture caches the environment on the remote to reduce rsync overhead, the Python environment often already exists when we do the project installation. When a remote orchestrator has been running for a while this could lead to issues where older versions of dependencies are already installed and are never upgraded.

Two potential solutions were already suggested (the second of which is probably the simplest and broadest, but further consideration is required):
- disable the cache when feasible, e.g. when `--use-module-in-place` is off
- make sure the modules and/or project installation on the remote uses `--upgrade --upgrade-strategy=eager`. Care should be taken that modules that are installed in editable mode aren't overwritten by the later project install with `--upgrade` and a test should be added for this scenario.

**Comment by sanderr** [comment]
Conclusion: `--upgrade` is expensive. Instead add `--lsm-cache` option.

**Comment by wouterdb** [comment]
To me, lsm-no-clean is about the behavior after the test (i.e. to not clean up after failure), so I would not could it with what happens before. 

Not caching between test session might be a good idea. 

So i agree, except for point 4.

**Comment by edvgui** [comment]
Fair enough.  Would an option like `lsm-keep-cache` having the behavior described in 4 make sense to you then?

**Comment by wouterdb** [comment]
I would just always clear out the folder before the test session, so 1,2,3

**Comment by sanderr** [comment]
Sounds good to me
