### ISSUE TITLE
Add service accepts any service

### ISSUE THREAD

**Issue by bartv** [inmanta/pytest-inmanta-lsm#354]
The [add service method](https://github.com/inmanta/pytest-inmanta-lsm/blob/master/src/pytest_inmanta_lsm/lsm_project.py#L238) accepts any service instance.

It should raise exceptions if it does not exist so that you can rely on lsm mocked tests for refactoring services.

**Comment by edvgui** [comment]
Closed by https://github.com/inmanta/pytest-inmanta-lsm/pull/391
